// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: console.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CapabilityId  string                 `protobuf:"bytes,2,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	Constraints   *structpb.Struct       `protobuf:"bytes,3,opt,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePolicyRequest) Reset() {
	*x = CreatePolicyRequest{}
	mi := &file_console_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyRequest) ProtoMessage() {}

func (x *CreatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyRequest.ProtoReflect.Descriptor instead.
func (*CreatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePolicyRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreatePolicyRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *CreatePolicyRequest) GetConstraints() *structpb.Struct {
	if x != nil {
		return x.Constraints
	}
	return nil
}

type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CapabilityId  string                 `protobuf:"bytes,3,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_console_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{1}
}

func (x *Policy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Policy) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Policy) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *Policy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ApprovalList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*ApprovalRequest     `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalList) Reset() {
	*x = ApprovalList{}
	mi := &file_console_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalList) ProtoMessage() {}

func (x *ApprovalList) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalList.ProtoReflect.Descriptor instead.
func (*ApprovalList) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{2}
}

func (x *ApprovalList) GetRequests() []*ApprovalRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type ApprovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalRequest) Reset() {
	*x = ApprovalRequest{}
	mi := &file_console_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRequest) ProtoMessage() {}

func (x *ApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRequest.ProtoReflect.Descriptor instead.
func (*ApprovalRequest) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{3}
}

func (x *ApprovalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApprovalRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ApprovalRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ApprovalRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type DecideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideRequest) Reset() {
	*x = DecideRequest{}
	mi := &file_console_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideRequest) ProtoMessage() {}

func (x *DecideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideRequest.ProtoReflect.Descriptor instead.
func (*DecideRequest) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{4}
}

func (x *DecideRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DecideRequest) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *DecideRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsRequest) Reset() {
	*x = AnalyticsRequest{}
	mi := &file_console_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsRequest) ProtoMessage() {}

func (x *AnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsRequest.ProtoReflect.Descriptor instead.
func (*AnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyticsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AnalyticsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *AnalyticsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type AnalyticsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalActions    int64                  `protobuf:"varint,1,opt,name=total_actions,json=totalActions,proto3" json:"total_actions,omitempty"`
	BlockedActions  int64                  `protobuf:"varint,2,opt,name=blocked_actions,json=blockedActions,proto3" json:"blocked_actions,omitempty"`
	TopCapabilities map[string]int64       `protobuf:"bytes,3,rep,name=top_capabilities,json=topCapabilities,proto3" json:"top_capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyticsResponse) Reset() {
	*x = AnalyticsResponse{}
	mi := &file_console_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsResponse) ProtoMessage() {}

func (x *AnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsResponse.ProtoReflect.Descriptor instead.
func (*AnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_console_proto_rawDescGZIP(), []int{6}
}

func (x *AnalyticsResponse) GetTotalActions() int64 {
	if x != nil {
		return x.TotalActions
	}
	return 0
}

func (x *AnalyticsResponse) GetBlockedActions() int64 {
	if x != nil {
		return x.BlockedActions
	}
	return 0
}

func (x *AnalyticsResponse) GetTopCapabilities() map[string]int64 {
	if x != nil {
		return x.TopCapabilities
	}
	return nil
}

var File_console_proto protoreflect.FileDescriptor

const file_console_proto_rawDesc = "" +
	"\n" +
	"\rconsole.proto\x12\n" +
	"console.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x90\x01\n" +
	"\x13CreatePolicyRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rcapability_id\x18\x02 \x01(\tR\fcapabilityId\x129\n" +
	"\vconstraints\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vconstraints\"\x93\x01\n" +
	"\x06Policy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12#\n" +
	"\rcapability_id\x18\x03 \x01(\tR\fcapabilityId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"G\n" +
	"\fApprovalList\x127\n" +
	"\brequests\x18\x01 \x03(\v2\x1b.console.v1.ApprovalRequestR\brequests\"y\n" +
	"\x0fApprovalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\"S\n" +
	"\rDecideRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x89\x01\n" +
	"\x10AnalyticsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"\x84\x02\n" +
	"\x11AnalyticsResponse\x12#\n" +
	"\rtotal_actions\x18\x01 \x01(\x03R\ftotalActions\x12'\n" +
	"\x0fblocked_actions\x18\x02 \x01(\x03R\x0eblockedActions\x12]\n" +
	"\x10top_capabilities\x18\x03 \x03(\v22.console.v1.AnalyticsResponse.TopCapabilitiesEntryR\x0ftopCapabilities\x1aB\n" +
	"\x14TopCapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\xb5\x02\n" +
	"\x0eConsoleService\x12C\n" +
	"\fCreatePolicy\x12\x1f.console.v1.CreatePolicyRequest\x1a\x12.console.v1.Policy\x12G\n" +
	"\x13GetPendingApprovals\x12\x16.google.protobuf.Empty\x1a\x18.console.v1.ApprovalList\x12C\n" +
	"\x0eDecideApproval\x12\x19.console.v1.DecideRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x11GetAgentAnalytics\x12\x1c.console.v1.AnalyticsRequest\x1a\x1d.console.v1.AnalyticsResponseBBZ@github.com/xela07ax/spaceai-infra-prototype/pkg/api/connector/v1b\x06proto3"

var (
	file_console_proto_rawDescOnce sync.Once
	file_console_proto_rawDescData []byte
)

func file_console_proto_rawDescGZIP() []byte {
	file_console_proto_rawDescOnce.Do(func() {
		file_console_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_console_proto_rawDesc), len(file_console_proto_rawDesc)))
	})
	return file_console_proto_rawDescData
}

var file_console_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_console_proto_goTypes = []any{
	(*CreatePolicyRequest)(nil),   // 0: console.v1.CreatePolicyRequest
	(*Policy)(nil),                // 1: console.v1.Policy
	(*ApprovalList)(nil),          // 2: console.v1.ApprovalList
	(*ApprovalRequest)(nil),       // 3: console.v1.ApprovalRequest
	(*DecideRequest)(nil),         // 4: console.v1.DecideRequest
	(*AnalyticsRequest)(nil),      // 5: console.v1.AnalyticsRequest
	(*AnalyticsResponse)(nil),     // 6: console.v1.AnalyticsResponse
	nil,                           // 7: console.v1.AnalyticsResponse.TopCapabilitiesEntry
	(*structpb.Struct)(nil),       // 8: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_console_proto_depIdxs = []int32{
	8,  // 0: console.v1.CreatePolicyRequest.constraints:type_name -> google.protobuf.Struct
	9,  // 1: console.v1.Policy.created_at:type_name -> google.protobuf.Timestamp
	3,  // 2: console.v1.ApprovalList.requests:type_name -> console.v1.ApprovalRequest
	9,  // 3: console.v1.AnalyticsRequest.from:type_name -> google.protobuf.Timestamp
	9,  // 4: console.v1.AnalyticsRequest.to:type_name -> google.protobuf.Timestamp
	7,  // 5: console.v1.AnalyticsResponse.top_capabilities:type_name -> console.v1.AnalyticsResponse.TopCapabilitiesEntry
	0,  // 6: console.v1.ConsoleService.CreatePolicy:input_type -> console.v1.CreatePolicyRequest
	10, // 7: console.v1.ConsoleService.GetPendingApprovals:input_type -> google.protobuf.Empty
	4,  // 8: console.v1.ConsoleService.DecideApproval:input_type -> console.v1.DecideRequest
	5,  // 9: console.v1.ConsoleService.GetAgentAnalytics:input_type -> console.v1.AnalyticsRequest
	1,  // 10: console.v1.ConsoleService.CreatePolicy:output_type -> console.v1.Policy
	2,  // 11: console.v1.ConsoleService.GetPendingApprovals:output_type -> console.v1.ApprovalList
	10, // 12: console.v1.ConsoleService.DecideApproval:output_type -> google.protobuf.Empty
	6,  // 13: console.v1.ConsoleService.GetAgentAnalytics:output_type -> console.v1.AnalyticsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_console_proto_init() }
func file_console_proto_init() {
	if File_console_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_proto_rawDesc), len(file_console_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_console_proto_goTypes,
		DependencyIndexes: file_console_proto_depIdxs,
		MessageInfos:      file_console_proto_msgTypes,
	}.Build()
	File_console_proto = out.File
	file_console_proto_goTypes = nil
	file_console_proto_depIdxs = nil
}
